name: Build and release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "version=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          docker run --rm -v $(pwd):/build -w /root alpine:latest /build/build.sh ${{ steps.vars.outputs.tag }}
      - name: Upload Release Asset
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "release/bcftools-*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
