name: Build and release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "version=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          docker run --rm -v $(pwd):/build -w /root alpine:latest /build/build.sh ${{ steps.vars.outputs.version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: Release ${{ steps.vars.outputs.version }}
          body: |
            ### Automated Release

            Static binaries compiled with the following dependencies:

            - htslib ${{ steps.vars.outputs.version }}
            - curl 8.1.2
            - openssl 3.1.1
            - libssh2 1.10.0
            - nghttp2 1.53.0
            - xz 5.4.3
            - zlib 1.2.13
            - bzip2 1.0.8
          draft: false
          prerelease: false
